### ISSUE TITLE
Landing page error when all the projects have no update

### ISSUE THREAD

**Issue by SeokbinKang** [jonfroehlich/makeabilitylabwebsite#332]
When there is no update on all the projects, the landing page fails in loading.

The problem is....
In views.py:371
"def get_most_recent(projects)" returns null value in this case.

I think this situation rarely happens though.

**Comment by jonfroehlich** [comment]
What do you mean by "all projects have no update"

**Comment by jonfroehlich** [comment]
Looks like maybe @mechanicjay is experiencing this same problem. He just sent me an email that said he came across this. Will try to fix now.

```
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/website/views.py", line 43, in index
    projects = get_most_recent(projects);
  File "/code/website/views.py", line 393, in get_most_recent
    print("project '{}' has the most recent artifact of {} updated {} and the check {}".format(item['proj'].name, mostRecentArtifact, mostRecentArtifact.date, item['updated']))
AttributeError: 'NoneType' object has no attribute 'date'
```

**Comment by jonfroehlich** [comment]
@SeokbinKang can you try it now and see if I fixed it?

**Comment by mechanicjay** [comment]
That fixed the error for me.

**Comment by jonfroehlich** [comment]
Thanks @mechanicjay.
