### ISSUE TITLE
Master No Longer Runs

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#341]
I think maybe this has to do with code @mechanicjay checked in where he added psycopg2 to requirements.txt. Error is below followed by my error I get when I try to install psycopg2.

```
makeabilitylabwebsite jonf$ python3 manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 176, in fetch_command
    commands = get_commands()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 71, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

```
makeabilitylabwebsite jonf$ pip3 install psycopg2
Collecting psycopg2
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1109b2128>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /simple/psycopg2/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1109b22e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /simple/psycopg2/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1109b2588>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /simple/psycopg2/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1109b2550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /simple/psycopg2/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1109b2cf8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /simple/psycopg2/
  Could not find a version that satisfies the requirement psycopg2 (from versions: )
No matching distribution found for psycopg2
```

**Comment by jonfroehlich** [comment]
I think this is resolved now... @aileenzeng, did you ever see this error? I can't even remember what I was talking about here... :-/

**Comment by aileenzeng** [comment]
I don't remember getting this error -- and it seems like we've been able to successfully set up the site a few times using Docker so I don't think it should be a problem anymore.

**Comment by jonfroehlich** [comment]
Great. Closing issue.
