### ISSUE TITLE
Test server isn't running (Server Error: 500)

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#361]
https://makeabilitylab-test.cs.washington.edu/ displays Server Error 500.
![image](https://user-images.githubusercontent.com/25534091/40571579-268cc416-6050-11e8-94ec-f16c797abea8.png)
Last known 'working' commit: `f7657afd7a8827c9c717cb18867b150dedc7d063`

**Comment by aileenzeng** [comment]
https://makeabilitylab-test.cs.washington.edu/admin/website/person/ also displays Server Error 500. (other admin pages seem to be fine)

**Comment by jonfroehlich** [comment]
@aileenzeng, can you please update this issue with the appropriate parts of the debug.log from the server. It seems to me that this is related to some changes you made to the Person model class and, perhaps, migrations not occurring correctly on the backend.

**Comment by aileenzeng** [comment]
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/website/views.py", line 225, in member
    person = get_object_or_404(Person, pk=member_id)
  File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 155, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 852, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column website_person.url_name does not exist
LINE 1: ...son"."middle_name", "website_person"."last_name", "website_p...
                                                             ^
```

**Comment by aileenzeng** [comment]
Something else worth mentioning: It seems like when makemigrations/migrate are being run (when I'm building the website locally), the url_name column is being added. This also is happening every time I build the website locally:
```
Migrations for 'website':
  0002_auto_20180530_1747.py:
    - Add field url_name to person
    - Alter field co_advisor on position
```
On the production side, it looks like neither of these fields are being updated (no changes are being made to the admin interface)

Local                                   |  Production
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/25534091/40749751-e21a841c-6419-11e8-8be5-ba44f2fb3943.png)  |  ![image](https://user-images.githubusercontent.com/25534091/40749756-e78ea428-6419-11e8-9425-80b730b95160.png)
![image](https://user-images.githubusercontent.com/25534091/40749847-393c08ec-641a-11e8-8e31-9a93c3937df6.png) | ![image](https://user-images.githubusercontent.com/25534091/40749888-6268095a-641a-11e8-94f5-d4cdf6bd343f.png)

**Comment by aileenzeng** [comment]
It's running now but is very fragile at the moment. Should be more stable once #366 is resolved.
