### ISSUE TITLE
Server Error 503 on test server

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#425]
![image](https://user-images.githubusercontent.com/25534091/42598111-12b8d92c-8510-11e8-9640-80f3f0520169.png)

Most of the WARNING messages seem to be coming from today, which is sort of odd since we didn't push to master today. I feel like there's something missing from the database (?), but I'm not sure. (Will post possibly relevant messages from `debug.log` below)

**Comment by jonfroehlich** [comment]
Thanks Aileen. I believe I did push a few small things to master yesterday

**Comment by aileenzeng** [comment]
I don't think they should have broken the site -- most of those were READMEs. I'm scrolling further up and there are also message from yesterday (but they seem unrelated from changes yesterday)

**Comment by aileenzeng** [comment]
Here are my hunches:
 1) Something went wrong with `models` or migrations or something from UW servers. We haven't changed models in any of our recent pull requests though.
2) There are things missing from the database. (less likely?)

I could also be missing the actual problem entirely; it seems like these issues have come up even before we made all those merges yesterday. It's totally possible that I scrolled past the actual issue (but the log is very dense/large).

Here's a summary of 2-3 types of issues that I keep seeing in the logs:

## Talks
There are a lot of these that end up triggering a lot of errors (EX: attribute errors) later on. This isn't specific talk either -- it seems to happen to a lot of them:

One example traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [total_papers_accepted] in 'Characterizing Physical World Accessibility at Scale Using Crowdsourcing, Computer Vision, and Machine Learning'
DEBUG 2018-07-10 18:16:10,231 base 127 140243466434304 Exception while resolving variable 'page_num_start' in template 'website/talks.html'.
```

Another example traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [video_url] in 'Making with a Social Purpose'
DEBUG 2018-07-10 18:16:10,255 base 127 140243466434304 Exception while resolving variable 'talk_venue_type' in template 'website/talks.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'Talk' object is not subscriptable
```

Various attribute errors that come up every now and then include:
```
AttributeError: 'Talk' object has no attribute 'to_appear'
AttributeError: 'Talk' object has no attribute 'video_url'
AttributeError: 'Talk' object has no attribute 'page_num_start'
AttributeError: 'Talk' object has no attribute 'award'
```

* It's kind of odd that it's complaining about these because `to_appear` is a function in Publications, and `video_url` is a field in Project_header and Video (etc...)

## Publications
Example traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [video_url] in 'None'
DEBUG 2018-07-10 18:15:53,250 base 127 140243466434304 Exception while resolving variable 'video_url' in template 'website/publications.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable
```
* Issues with publications mostly have to do with TypeErrors from `NoneType`.

## Landing page errors?
There are sort of difficult to track down, since there are so many things going on in the landing page. I'm guessing these have to do with errors on Talks/Publications, but I'm not sure. There are a lot of issues with `NoneType` objects which also make them difficult to track down. 

One example:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [pdf_file] in 'None'
DEBUG 2018-07-10 19:33:50,373 base 127 140243466434304 Exception while resolving variable 'video_url' in template 'website/index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'video_url'
```

**Comment by aileenzeng** [comment]
There are also a lot of issues that pop up when I do searches of `can_delete_related` and `can_change_related` in the log. Maybe this is a Django issue then? These seem to be recent changes, so maybe they're the ones that are causing the site to break:

One example traceback (big wall of text!)
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [can_delete_related] in '[{\'True\': True, \'False\': False, \'None\': None}, {\'widget\': \'<select id="id_video" name="video">\\n<option value="" selected="selected">---------</option>\\n<option value="35">TouchCam: Realtime Recognition of Location-Specific On-Body Gestures to Support Users with Visual Impairments</option>\\n<option value="34">MakerWear: A Tangible Approach to Interactive Wearable Creation for Children</option>\\n<option value="36">Introducing Project Sidewalk: Mapping the Accessibility of the World</option>\\n<option value="33">SqueezaPulse: Adding Interactive Input to Fabricated Objects Using Corrugated Tubes and Air Pulses</option>\\n<option value="31">SharedPhys: Live Physiological Sensing, Whole-Body Interaction, and Large-Screen Visualizations to Support Shared Inquiry Experiences</option>\\n<option value="32">Characterizing Street-level Accessibility at Scale</option>\\n<option value="15">BodyVis CHI 2015 Conference Presentation Leyla Norooz</option>\\n<option value="28">AtmoSPHERE: Representing Space and Movement Using Sand Traces in an Interactive Zen Garden</option>\\n<option value="23">BodyVis: A New Approach to Body Learning Through Wearable Sensing and Visualization</option>\\n<option value="25">Understanding the Role of Thermography in Energy Auditing: Current Practices and the Potential for Automated Solutions</option>\\n<option value="29">Understanding the Role of Thermography in Energy Auditing: Current Practices and the Potential for Automated Solutions</option>\\n<option value="24">Head-Mounted Display Visualizations to Support Sound Awareness for the Deaf and Hard of Hearing</option>\\n<option value="27">The Design and Preliminary Evaluation of a Finger-Mounted Camera and Feedback System to Enable Reading of Printed Text for the Blind</option>\\n<option value="26">Social Fabric Fitness: The Design and Evaluation of Wearable E-Textile Displays to Support Group Running</option>\\n<option value="30">Social Fabric Fitness: The Design and Evaluation of Wearable E-Textile Displays to Support Group Running</option>\\n</select>\', \'name\': \'video\', \'url_params\': \'_to_field=id&_popup=1\', \'model\': \'video\', \'can_change_related\': True, \'change_related_template_url\': \'/admin/website/video/__fk__/change/\', \'can_add_related\': True, \'add_related_url\': \'/admin/website/video/add/\'}, {\'block\': <Block Node: links. Contents: [<TextNode: \'\\n        \'>, <IfNode>, <TextNode: \'\\n        \'>, <IfNode>, <TextNode: \'\\n        \'>, <IfNode>, <TextNode: \'\\n    \'>]>}]'
DEBUG 2018-07-11 16:23:26,582 base 127 140243466434304 Exception while resolving variable 'can_delete_related' in template 'admin/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.6/site-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'can_delete_related'
```

**Comment by mechanicjay** [comment]
Sorry this was my fault, the host machine crashed and docker didn't come back up properly on reboot.  Should be good now.

**Comment by aileenzeng** [comment]
Oh that’s great - thanks so much!

**Comment by jonfroehlich** [comment]
Hahah, my team didn't want to bother you @mechanicjay until we had investigated ourselves, which is why we didn't already reach out to you... but lesson learned! :)
