### ISSUE TITLE
Hmm, css not loading on admin site?

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#575]
![image](https://user-images.githubusercontent.com/1621749/44291199-a9c29900-a231-11e8-9759-24ada5df25f3.png)

@johnsonkuang, are you seeing this too?

**Comment by johnsonkuang** [comment]
@mechanicjay

**Comment by aileenzeng** [comment]
Got this when I tried to click on person (from the admin site):
![image](https://user-images.githubusercontent.com/25534091/44291429-26a24280-a233-11e8-9c6d-f0365fe6ea7d.png)

**Comment by jonfroehlich** [comment]
@aileenzeng, pretty sure that's unrelated. Works for me. CSS still not loading on admin site though.

**Comment by jonfroehlich** [comment]
Just checked again. Still a problem.

![image](https://user-images.githubusercontent.com/1621749/44605769-6cb15600-a79f-11e8-913d-4eb799d240a8.png)

**Comment by johnsonkuang** [comment]
I think it's a permission issue that Docker is not allowing Django to access the static files folder inside the container. I get this error locally:
```
Collecting static files
Copying '/code/website/static/website/css/autocomplete.css'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 189, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    handler(path, prefixed_path, storage)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 354, in copy_file
    self.storage.save(prefixed_path, source_file)
  File "/usr/local/lib/python3.7/site-packages/django/core/files/storage.py", line 49, in save
    return self._save(name, content)
  File "/usr/local/lib/python3.7/site-packages/django/core/files/storage.py", line 236, in _save
    os.makedirs(directory)
  File "/usr/local/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/code/static'
```

**Comment by jonfroehlich** [comment]
@aileenzeng, thoughts on this.

**Comment by aileenzeng** [comment]
Hmm I haven't seen this before. Maybe we could add a line in our Dockerfile to make sure we have the correct permissions. I'd imagine the line would be something like this, but I haven't really looked into it yet: `RUN chown <something> /code/static`

**Comment by jonfroehlich** [comment]
I wonder what happened to cause this problem though since things were working before. It’s not like we had to mess around with permissions in the past for this. It’s notable that we’re experiencing this problem locally as well as on the server. Hopefully, that means it’ll be easier to track down and fix and verify that we fixed it

**Comment by aileenzeng** [comment]
Here's the current permissions line in our Dockerfile:
```
##Our local user needs write access to a place
RUN chown apache /code/website
```

We could change it to this instead:
```
##Our local user needs write access to a place
RUN chown apache /code
``` 
This works locally for me -- I don't get the permissions error anymore. (`/code` is our working directory, so it's the root directory of our Django project).

 I don't know if this is the best solution because there's all sorts of other stuff in the root directory (database, all of our media...) and I don't know if there's a reason we're not giving apache access to those right now.

**Comment by jonfroehlich** [comment]
Let's change it for now (so we can try to get css to load again on admin, so we can start filling content again). And we can loop back and ask @mechanicjay once he's back from vacation.

Sound good?

**Comment by aileenzeng** [comment]
This issue is fixed now.

**Comment by jonfroehlich** [comment]
Thanks!
