### ISSUE TITLE
Can't connect to database on local environment

### ISSUE THREAD

**Issue by aileenzeng** [jonfroehlich/makeabilitylabwebsite#597]
I'm running a clean copy of the dev environment (reset Docker to factory settings + re-cloned the git repository) and am getting this error when I try to run my docker container or try to connect to the database.

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fa763d95ea0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 162, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file
```

I think I've tracked it down to e76664f00bc33f62fa6eb3e36b720d47f3d3fc22 (PR #561).

**Comment by jonfroehlich** [comment]
Ooooh. I wonder if this is related to our static css permissions problem too!
