### ISSUE TITLE
Publications not loading

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#603]
I just added the following publication and now the publications page is not loading.

![image](https://user-images.githubusercontent.com/1621749/46178609-63b71700-c26c-11e8-8b3f-7edb7e29178a.png)

![image](https://user-images.githubusercontent.com/1621749/46178562-408c6780-c26c-11e8-8aeb-68cb628ade12.png)

**Comment by jonfroehlich** [comment]
Error log says this:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
>     current = getattr(current, bit)
> AttributeError: 'NoneType' object has no attribute 'pdf_file'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
>     current = current[int(bit)]
> ValueError: invalid literal for int() with base 10: 'pdf_file'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
>     (bit, current))  # missing attribute
> django.template.base.VariableDoesNotExist: Failed lookup for key [pdf_file] in None
> INFO 2018-09-27 18:51:17,302 basehttp 131 139699423053568 "GET / HTTP/1.1" 200 87162

**Comment by jonfroehlich** [comment]
More updates. I've tracked it down to the special characters in the authors names, in particular: 'João Guerreiro' and ' Johannes Schöning.'

> NoReverseMatch
> Reverse for 'member' with arguments '('joãoguerreiro',)' not found. 4 pattern(s) tried: ['member/(?P<member_id>[-a-z]+)\\.(?P<format>[a-z0-9]+)/?$', 'member/(?P<member_id>[-a-z]+)/$', 'member/(?P<member_id>[0-9]+)\\.(?P<format>[a-z0-9]+)/?$', 'member/(?P<member_id>[0-9]+)/$']
> /usr/local/lib/python3.6/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 636
> /usr/local/bin/python
> 3.6.3
> ['/code',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages']
> Thu, 27 Sep 2018 19:09:48 -0400
> 

I think this might be related to @aileenzeng's new member url code from this summer?

> Full log:
> 
> Environment:
> 
> 
> Request Method: GET
> Request URL: http://localhost:8000/publications/
> 
> Django Version: 2.0.7
> Python Version: 3.6.3
> Installed Applications:
> ['website.apps.WebsiteConfig',
>  'django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'django_extensions',
>  'image_cropping',
>  'easy_thumbnails',
>  'sortedm2m',
>  'sortedm2m_filter_horizontal_widget',
>  'rest_framework']
> Installed Middleware:
> ['django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware']
> 
> 
> Template error:
> In template /code/website/templates/website/base.html, error at line 0
>    Reverse for 'member' with arguments '('joãoguerreiro',)' not found. 4 pattern(s) tried: ['member/(?P<member_id>[-a-z]+)\\.(?P<format>[a-z0-9]+)/?$', 'member/(?P<member_id>[-a-z]+)/$', 'member/(?P<member_id>[0-9]+)\\.(?P<format>[a-z0-9]+)/?$', 'member/(?P<member_id>[0-9]+)/$']
>    1 : <!DOCTYPE html>
>    2 : <html lang="en">
>    3 : <head>
>    4 :     <meta charset="UTF-8">
>    5 :     <meta http-equiv="X-UA-Compatible" content="IE=edge">
>    6 :     <meta name="viewport" content="width=device-width, initial-scale=1">
>    7 :     <meta name="description" content="">
>    8 :     <meta name="author" content="">
>    9 : 
>    10 :     {% load staticfiles %}
> 
> 
> Traceback:
> 
> File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
>   35.             response = get_response(request)
> 
> File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
>   128.                 response = self.process_exception_by_middleware(e, request)
> 
> File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
>   126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
> File "/code/website/views.py" in publications
>   401.     return render(request, 'website/publications.html', context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py" in render
>   36.     content = loader.render_to_string(template_name, context, request, using=using)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/loader.py" in render_to_string
>   62.     return template.render(context, request)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py" in render
>   61.             return self.template.render(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render
>   175.                     return self._render(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in _render
>   167.         return self.nodelist.render(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render
>   943.                 bit = node.render_annotated(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render_annotated
>   910.             return self.render(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py" in render
>   155.             return compiled_parent._render(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in _render
>   167.         return self.nodelist.render(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render
>   943.                 bit = node.render_annotated(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render_annotated
>   910.             return self.render(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py" in render
>   67.                 result = block.nodelist.render(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render
>   943.                 bit = node.render_annotated(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render_annotated
>   910.             return self.render(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py" in render
>   211.                     nodelist.append(node.render_annotated(context))
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render_annotated
>   910.             return self.render(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py" in render
>   211.                     nodelist.append(node.render_annotated(context))
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/base.py" in render_annotated
>   910.             return self.render(context)
> 
> File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py" in render
>   447.             url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
> 
> File "/usr/local/lib/python3.6/site-packages/django/urls/base.py" in reverse
>   90.     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
> 
> File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py" in _reverse_with_prefix
>   636.         raise NoReverseMatch(msg)
> 
> Exception Type: NoReverseMatch at /publications/
> Exception Value: Reverse for 'member' with arguments '('joãoguerreiro',)' not found. 4 pattern(s) tried: ['member/(?P<member_id>[-a-z]+)\\.(?P<format>[a-z0-9]+)/?$', 'member/(?P<member_id>[-a-z]+)/$', 'member/(?P<member_id>[0-9]+)\\.(?P<format>[a-z0-9]+)/?$', 'member/(?P<member_id>[0-9]+)/$']

**Comment by jonfroehlich** [comment]
As a temporary fix, I changed 'João Guerreiro' to 'Joao Guerreiro' and 'Johannes Schöning' to  'Johannes Schoning.' However, ideally, we'd be able to use the correct special characters in their name.
