### ISSUE TITLE
When I try to change a person's position, I get a server error

### ISSUE THREAD

**Issue by jonfroehlich** [jonfroehlich/makeabilitylabwebsite#605]
When I try to change a person's position, I get a server error:

![image](https://user-images.githubusercontent.com/1621749/46226138-3328b900-c310-11e8-9015-73ad23079893.png)

Log file:

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 841, in _resolve_lookup
>     if isinstance(current, BaseContext) and getattr(type(current), bit):
> AttributeError: type object 'Context' has no attribute 'can_delete_related'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 849, in _resolve_lookup
>     current = current[int(bit)]
> ValueError: invalid literal for int() with base 10: 'can_delete_related'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
>     (bit, current))  # missing attribute
> django.template.base.VariableDoesNotExist: Failed lookup for key [can_delete_related] in [{'True': True, 'False': False, 'None': None}, {'rendered_widget': '<select name="project_role_set-__prefix__-project" id="id_project_role_set-__prefix__-project">\n  <option value="" selected>---------</option>\n\n  <option value="7">Touchscreen Accessibility</option>\n\n  <option value="8">HydroSense: Sensing &amp; Visualizing Fixture-Level Water Usage</option>\n\n  <option value="2">HandSight</option>\n\n  <option value="6">Social Fabric Fitness</option>\n\n  <option value="9">MakerWear</option>\n\n  <option value="3">Project Sidewalk</option>\n\n  <option value="10">SqueezaPulse</option>\n\n  <option value="11">Ondulé</option>\n\n  <option value="4">GlassEar</option>\n\n  <option value="5">Scalable Thermography</option>\n\n  <option value="12">Accessibility Literature Survey</option>\n\n  <option value="1">BodyVis</option>\n\n  <option value="13">Rainbow</option>\n\n</select>', 'name': 'project_role_set-__prefix__-project', 'url_params': '_to_field=id&_popup=1', 'model': 'project', 'can_change_related': True, 'change_related_template_url': '/admin/website/project/__fk__/change/', 'can_add_related': True, 'add_related_url': '/admin/website/project/add/'}, {'block': <Block Node: links. Contents: [<TextNode: '\n        '>, <django.template.defaulttags.SpacelessNode object at 0x7f20330cabe0>, <TextNode: '\n    '>]>}]
> INFO 2018-09-28 14:17:36,515 basehttp 129 139776283825920 "GET /admin/website/person/278/change/?_changelist_filters=position_role%3Dcurrent_collaborator HTTP/1.1" 200 69328
> INFO 2018-09-28 14:17:36,545 basehttp 129 139776283825920 "GET /admin/jsi18n/ HTTP/1.1" 200 3185
> ERROR 2018-09-28 14:17:51,216 exception 129 139776283825920 Internal Server Error: /admin/website/person/278/change/
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 575, in wrapper
>     return self.admin_site.admin_view(view)(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
>     return view(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1557, in change_view
>     return self.changeform_view(request, object_id, form_url, extra_context)
>   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 62, in _wrapper
>     return bound_func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 58, in bound_func
>     return func.__get__(self, type(self))(*args2, **kwargs2)
>   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1451, in changeform_view
>     return self._changeform_view(request, object_id, form_url, extra_context)
>   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1490, in _changeform_view
>     if all_valid(formsets) and form_validated:
>   File "/usr/local/lib/python3.6/site-packages/django/forms/formsets.py", line 442, in all_valid
>     if not formset.is_valid():
>   File "/usr/local/lib/python3.6/site-packages/django/forms/formsets.py", line 301, in is_valid
>     self.errors
>   File "/usr/local/lib/python3.6/site-packages/django/forms/formsets.py", line 281, in errors
>     self.full_clean()
>   File "/usr/local/lib/python3.6/site-packages/django/forms/formsets.py", line 329, in full_clean
>     form_errors = form.errors
>   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 174, in errors
>     self.full_clean()
>   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 378, in full_clean
>     self._post_clean()
>   File "/usr/local/lib/python3.6/site-packages/django/forms/models.py", line 401, in _post_clean
>     self.instance.full_clean(exclude=exclude, validate_unique=False)
>   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 1151, in full_clean
>     self.clean()
>   File "/code/website/models.py", line 434, in clean
>     if not self.start_date < self.end_date:
> TypeError: '<' not supported between instances of 'datetime.date' and 'NoneType'
> ERROR 2018-09-28 14:17:51,227 basehttp 129 139776283825920 "POST /admin/website/person/278/change/?_changelist_filters=position_role%3Dcurrent_collaborator HTTP/1.1" 500 27

**Comment by jonfroehlich** [comment]
Fixed here https://github.com/jonfroehlich/makeabilitylabwebsite/commit/26697e4a97d1b916ade541e80cbedc32a7cb30a5
